[2025-05-14T11:31:13.706+0100] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_bank_reviews.run_decision_models manual__2025-05-13T23:44:36.782331+00:00 [queued]>
[2025-05-14T11:31:13.732+0100] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_bank_reviews.run_decision_models manual__2025-05-13T23:44:36.782331+00:00 [queued]>
[2025-05-14T11:31:13.735+0100] {taskinstance.py:2170} INFO - Starting attempt 5 of 5
[2025-05-14T11:31:13.801+0100] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): run_decision_models> on 2025-05-13 23:44:36.782331+00:00
[2025-05-14T11:31:13.832+0100] {standard_task_runner.py:60} INFO - Started process 81530 to run task
[2025-05-14T11:31:13.841+0100] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'process_bank_reviews', 'run_decision_models', 'manual__2025-05-13T23:44:36.782331+00:00', '--job-id', '1905', '--raw', '--subdir', 'DAGS_FOLDER/post_processing.py', '--cfg-path', '/tmp/tmpi9f6jnbd']
[2025-05-14T11:31:13.847+0100] {standard_task_runner.py:88} INFO - Job 1905: Subtask run_decision_models
[2025-05-14T11:31:13.967+0100] {task_command.py:423} INFO - Running <TaskInstance: process_bank_reviews.run_decision_models manual__2025-05-13T23:44:36.782331+00:00 [running]> on host DESKTOP-RRUTCI2.
[2025-05-14T11:31:14.173+0100] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='process_bank_reviews' AIRFLOW_CTX_TASK_ID='run_decision_models' AIRFLOW_CTX_EXECUTION_DATE='2025-05-13T23:44:36.782331+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-13T23:44:36.782331+00:00'
[2025-05-14T11:31:14.180+0100] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-14T11:31:14.183+0100] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd ~/airflow/dbt_project/decision_schema && dbt run']
[2025-05-14T11:31:14.209+0100] {subprocess.py:86} INFO - Output:
[2025-05-14T11:31:14.213+0100] {subprocess.py:93} INFO - /usr/bin/bash: line 0: cd: /home/osama/airflow/dbt_project/decision_schema: No such file or directory
[2025-05-14T11:31:14.215+0100] {subprocess.py:97} INFO - Command exited with return code 1
[2025-05-14T11:31:14.253+0100] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/mnt/c/Users/HP/venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/mnt/c/Users/HP/venv/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-05-14T11:31:14.274+0100] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=process_bank_reviews, task_id=run_decision_models, execution_date=20250513T234436, start_date=20250514T103113, end_date=20250514T103114
[2025-05-14T11:31:14.305+0100] {standard_task_runner.py:107} ERROR - Failed to execute job 1905 for task run_decision_models (Bash command failed. The command returned a non-zero exit code 1.; 81530)
[2025-05-14T11:31:14.335+0100] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-05-14T11:31:14.386+0100] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
