[2025-05-14T11:06:31.487+0100] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_bank_reviews.run_clean_reviews manual__2025-05-13T23:44:36.782331+00:00 [queued]>
[2025-05-14T11:06:31.508+0100] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_bank_reviews.run_clean_reviews manual__2025-05-13T23:44:36.782331+00:00 [queued]>
[2025-05-14T11:06:31.510+0100] {taskinstance.py:2170} INFO - Starting attempt 3 of 3
[2025-05-14T11:06:31.539+0100] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): run_clean_reviews> on 2025-05-13 23:44:36.782331+00:00
[2025-05-14T11:06:31.550+0100] {standard_task_runner.py:60} INFO - Started process 73596 to run task
[2025-05-14T11:06:31.557+0100] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'process_bank_reviews', 'run_clean_reviews', 'manual__2025-05-13T23:44:36.782331+00:00', '--job-id', '1899', '--raw', '--subdir', 'DAGS_FOLDER/post_processing.py', '--cfg-path', '/tmp/tmptk0314f7']
[2025-05-14T11:06:31.562+0100] {standard_task_runner.py:88} INFO - Job 1899: Subtask run_clean_reviews
[2025-05-14T11:06:31.689+0100] {task_command.py:423} INFO - Running <TaskInstance: process_bank_reviews.run_clean_reviews manual__2025-05-13T23:44:36.782331+00:00 [running]> on host DESKTOP-RRUTCI2.
[2025-05-14T11:06:31.932+0100] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='process_bank_reviews' AIRFLOW_CTX_TASK_ID='run_clean_reviews' AIRFLOW_CTX_EXECUTION_DATE='2025-05-13T23:44:36.782331+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-13T23:44:36.782331+00:00'
[2025-05-14T11:06:31.939+0100] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-14T11:06:31.942+0100] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd ~/airflow/dbt_project && dbt run --select clean_bank_reviews']
[2025-05-14T11:06:31.974+0100] {subprocess.py:86} INFO - Output:
[2025-05-14T11:06:56.912+0100] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2025-05-14T11:06:56.934+0100] {process_utils.py:131} INFO - Sending 15 to group 73596. PIDs of all processes in the group: [73604, 73596]
[2025-05-14T11:06:56.937+0100] {process_utils.py:86} INFO - Sending the signal 15 to group 73596
[2025-05-14T11:06:56.940+0100] {taskinstance.py:2450} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-05-14T11:06:56.943+0100] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2025-05-14T11:06:56.995+0100] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/mnt/c/Users/HP/venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/mnt/c/Users/HP/venv/lib/python3.8/site-packages/airflow/operators/bash.py", line 203, in execute
    result = self.subprocess_hook.run_command(
  File "/mnt/c/Users/HP/venv/lib/python3.8/site-packages/airflow/hooks/subprocess.py", line 91, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b""):
  File "/mnt/c/Users/HP/venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2452, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2025-05-14T11:06:57.159+0100] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=process_bank_reviews, task_id=run_clean_reviews, execution_date=20250513T234436, start_date=20250514T100631, end_date=20250514T100657
[2025-05-14T11:06:57.216+0100] {standard_task_runner.py:107} ERROR - Failed to execute job 1899 for task run_clean_reviews (Task received SIGTERM signal; 73596)
[2025-05-14T11:06:57.235+0100] {process_utils.py:79} INFO - Process psutil.Process(pid=73604, status='terminated', started='11:06:31') (73604) terminated with exit code None
[2025-05-14T11:06:57.238+0100] {process_utils.py:79} INFO - Process psutil.Process(pid=73596, status='terminated', exitcode=1, started='11:06:31') (73596) terminated with exit code 1
